services:
  # The Django Backend
  - type: web
    name: cavista-backend
    env: python
    region: ohio
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cavista-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "<YOUR_NETLIFY_FRONTEND_URL_HERE>" # You will need to update this after deploying the frontend
      - key: GEMINI_API_KEY
        value: "<YOUR_GEMINI_API_KEY_HERE>" # Update in Render dashboard
      - key: FIELD_ENCRYPTION_KEY
        value: "<YOUR_FERNET_KEY_HERE>" # Generate using pgcrypto or Fernet

databases:
  # Free tier PostgreSQL database
  - name: cavista-db
    databaseName: cavista
    user: cavista_user
    plan: free # using the free tier
